name: Auto Sign

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run skyland.py
      env:
        GitHub_Actions: true
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        python skyland.py
